<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">
 
    <!-- Radar support -->
    <xacro:property name="support_length" value="0.15" /> <!-- support length -->
    <xacro:property name="support_radius" value="0.01" /> <!-- support radius -->
    <xacro:property name="support_x" value="0.0" /> <!-- x coordinate of support installation -->
    <xacro:property name="support_y" value="0.0" /> <!-- y coordinate of support installation -->
    <xacro:property name="support_z" value="${base_link_length / 2 + support_length / 2}" /> <!-- Z coordinate of support installation: support length / 2 + support height / 2  -->
    <xacro:property name="support_m" value="0.02" /> <!-- Support quality -->
 
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="red">
                <color rgba="0.8 0.2 0.0 0.8" />
            </material>
        </visual>
 
        <collision>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
 
        <xacro:cylinder_inertial_matrix m="${support_m}" r="${support_radius}" h="${support_length}" />
    </link>
 
    <joint name="support2base_link" type="fixed">
        <parent link="base_link" />
        <child link="support" />
        <origin xyz="${support_x} ${support_y} ${support_z}" />
    </joint>
 
    <gazebo reference="support">
        <material>Gazebo/White</material>
    </gazebo>
 
    <!-- Radar properties -->
    <xacro:property name="laser_length" value="0.05" /> <!-- radar length -->
    <xacro:property name="laser_radius" value="0.03" /> <!-- Radar radius -->
    <xacro:property name="laser_x" value="0.0" /> <!-- x coordinates of the radar installation -->
    <xacro:property name="laser_y" value="0.0" /> <!-- y coordinates of the radar installation -->
    <xacro:property name="laser_z" value="${support_length / 2 + laser_length / 2}" /> <!-- Z coordinates of radar installation: support height / 2 + radar height / 2  -->
    <xacro:property name="laser_m" value="0.1" /> <!-- Radar quality -->
 
    <!-- Radar joints and Link -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
    </link>
 
    <joint name="laser2support" type="fixed">
        <parent link="support" />
        <child link="laser" />
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" />
    </joint>
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>
